'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
'
Namespace ar.com.openhex
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ohWSDLBinding", [Namespace]:="urn:ohWDSL")>  _
    Partial Public Class ohWSDL
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private wsvo_autorizarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private wsvo_anularOperationCompleted As System.Threading.SendOrPostCallback
        
        Private wsvo_verificar_afiliadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WebService_Tester.My.MySettings.Default.WebService_Tester_ar_com_openhex_ohWSDL
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event wsvo_autorizarCompleted As wsvo_autorizarCompletedEventHandler
        
        '''<remarks/>
        Public Event wsvo_anularCompleted As wsvo_anularCompletedEventHandler
        
        '''<remarks/>
        Public Event wsvo_verificar_afiliadoCompleted As wsvo_verificar_afiliadoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsWSDL#autorizar", RequestNamespace:="urn:wsWSDL", ResponseNamespace:="urn:wsWSDL")>  _
        Public Function wsvo_autorizar( _
                    ByVal financiador As String,  _
                    ByVal usr As String,  _
                    ByVal pwd As String,  _
                    ByVal afiliado As String,  _
                    ByVal id_empresa As Integer,  _
                    ByVal id_prestador As Integer,  _
                    ByVal cantidad_1 As Integer,  _
                    ByVal practica_1 As Decimal,  _
                    ByVal cantidad_2 As Integer,  _
                    ByVal practica_2 As Decimal,  _
                    ByVal cantidad_3 As Integer,  _
                    ByVal practica_3 As Decimal,  _
                    ByVal cantidad_4 As Integer,  _
                    ByVal practica_4 As Decimal,  _
                    ByVal cantidad_5 As Integer,  _
                    ByVal practica_5 As Decimal,  _
                    ByVal cantidad_6 As Integer,  _
                    ByVal practica_6 As Decimal,  _
                    ByVal cantidad_7 As Integer,  _
                    ByVal practica_7 As Decimal,  _
                    ByVal cantidad_8 As Integer,  _
                    ByVal practica_8 As Decimal,  _
                    ByVal cantidad_9 As Integer,  _
                    ByVal practica_9 As Decimal,  _
                    ByVal cantidad_10 As Integer,  _
                    ByVal practica_10 As Decimal,  _
                    ByVal cantidad_11 As Integer,  _
                    ByVal practica_11 As Decimal,  _
                    ByVal cantidad_12 As Integer,  _
                    ByVal practica_12 As Decimal,  _
                    ByVal cantidad_13 As Integer,  _
                    ByVal practica_13 As Decimal,  _
                    ByVal cantidad_14 As Integer,  _
                    ByVal practica_14 As Decimal,  _
                    ByVal cantidad_15 As Integer,  _
                    ByVal practica_15 As Decimal,  _
                    ByVal cantidad_16 As Integer,  _
                    ByVal practica_16 As Decimal,  _
                    ByVal cantidad_17 As Integer,  _
                    ByVal practica_17 As Decimal,  _
                    ByVal cantidad_18 As Integer,  _
                    ByVal practica_18 As Decimal,  _
                    ByVal cantidad_19 As Integer,  _
                    ByVal practica_19 As Decimal,  _
                    ByVal cantidad_20 As Integer,  _
                    ByVal practica_20 As Decimal) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("wsvo_autorizar", New Object() {financiador, usr, pwd, afiliado, id_empresa, id_prestador, cantidad_1, practica_1, cantidad_2, practica_2, cantidad_3, practica_3, cantidad_4, practica_4, cantidad_5, practica_5, cantidad_6, practica_6, cantidad_7, practica_7, cantidad_8, practica_8, cantidad_9, practica_9, cantidad_10, practica_10, cantidad_11, practica_11, cantidad_12, practica_12, cantidad_13, practica_13, cantidad_14, practica_14, cantidad_15, practica_15, cantidad_16, practica_16, cantidad_17, practica_17, cantidad_18, practica_18, cantidad_19, practica_19, cantidad_20, practica_20})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub wsvo_autorizarAsync( _
                    ByVal financiador As String,  _
                    ByVal usr As String,  _
                    ByVal pwd As String,  _
                    ByVal afiliado As String,  _
                    ByVal id_empresa As Integer,  _
                    ByVal id_prestador As Integer,  _
                    ByVal cantidad_1 As Integer,  _
                    ByVal practica_1 As Decimal,  _
                    ByVal cantidad_2 As Integer,  _
                    ByVal practica_2 As Decimal,  _
                    ByVal cantidad_3 As Integer,  _
                    ByVal practica_3 As Decimal,  _
                    ByVal cantidad_4 As Integer,  _
                    ByVal practica_4 As Decimal,  _
                    ByVal cantidad_5 As Integer,  _
                    ByVal practica_5 As Decimal,  _
                    ByVal cantidad_6 As Integer,  _
                    ByVal practica_6 As Decimal,  _
                    ByVal cantidad_7 As Integer,  _
                    ByVal practica_7 As Decimal,  _
                    ByVal cantidad_8 As Integer,  _
                    ByVal practica_8 As Decimal,  _
                    ByVal cantidad_9 As Integer,  _
                    ByVal practica_9 As Decimal,  _
                    ByVal cantidad_10 As Integer,  _
                    ByVal practica_10 As Decimal,  _
                    ByVal cantidad_11 As Integer,  _
                    ByVal practica_11 As Decimal,  _
                    ByVal cantidad_12 As Integer,  _
                    ByVal practica_12 As Decimal,  _
                    ByVal cantidad_13 As Integer,  _
                    ByVal practica_13 As Decimal,  _
                    ByVal cantidad_14 As Integer,  _
                    ByVal practica_14 As Decimal,  _
                    ByVal cantidad_15 As Integer,  _
                    ByVal practica_15 As Decimal,  _
                    ByVal cantidad_16 As Integer,  _
                    ByVal practica_16 As Decimal,  _
                    ByVal cantidad_17 As Integer,  _
                    ByVal practica_17 As Decimal,  _
                    ByVal cantidad_18 As Integer,  _
                    ByVal practica_18 As Decimal,  _
                    ByVal cantidad_19 As Integer,  _
                    ByVal practica_19 As Decimal,  _
                    ByVal cantidad_20 As Integer,  _
                    ByVal practica_20 As Decimal)
            Me.wsvo_autorizarAsync(financiador, usr, pwd, afiliado, id_empresa, id_prestador, cantidad_1, practica_1, cantidad_2, practica_2, cantidad_3, practica_3, cantidad_4, practica_4, cantidad_5, practica_5, cantidad_6, practica_6, cantidad_7, practica_7, cantidad_8, practica_8, cantidad_9, practica_9, cantidad_10, practica_10, cantidad_11, practica_11, cantidad_12, practica_12, cantidad_13, practica_13, cantidad_14, practica_14, cantidad_15, practica_15, cantidad_16, practica_16, cantidad_17, practica_17, cantidad_18, practica_18, cantidad_19, practica_19, cantidad_20, practica_20, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub wsvo_autorizarAsync( _
                    ByVal financiador As String,  _
                    ByVal usr As String,  _
                    ByVal pwd As String,  _
                    ByVal afiliado As String,  _
                    ByVal id_empresa As Integer,  _
                    ByVal id_prestador As Integer,  _
                    ByVal cantidad_1 As Integer,  _
                    ByVal practica_1 As Decimal,  _
                    ByVal cantidad_2 As Integer,  _
                    ByVal practica_2 As Decimal,  _
                    ByVal cantidad_3 As Integer,  _
                    ByVal practica_3 As Decimal,  _
                    ByVal cantidad_4 As Integer,  _
                    ByVal practica_4 As Decimal,  _
                    ByVal cantidad_5 As Integer,  _
                    ByVal practica_5 As Decimal,  _
                    ByVal cantidad_6 As Integer,  _
                    ByVal practica_6 As Decimal,  _
                    ByVal cantidad_7 As Integer,  _
                    ByVal practica_7 As Decimal,  _
                    ByVal cantidad_8 As Integer,  _
                    ByVal practica_8 As Decimal,  _
                    ByVal cantidad_9 As Integer,  _
                    ByVal practica_9 As Decimal,  _
                    ByVal cantidad_10 As Integer,  _
                    ByVal practica_10 As Decimal,  _
                    ByVal cantidad_11 As Integer,  _
                    ByVal practica_11 As Decimal,  _
                    ByVal cantidad_12 As Integer,  _
                    ByVal practica_12 As Decimal,  _
                    ByVal cantidad_13 As Integer,  _
                    ByVal practica_13 As Decimal,  _
                    ByVal cantidad_14 As Integer,  _
                    ByVal practica_14 As Decimal,  _
                    ByVal cantidad_15 As Integer,  _
                    ByVal practica_15 As Decimal,  _
                    ByVal cantidad_16 As Integer,  _
                    ByVal practica_16 As Decimal,  _
                    ByVal cantidad_17 As Integer,  _
                    ByVal practica_17 As Decimal,  _
                    ByVal cantidad_18 As Integer,  _
                    ByVal practica_18 As Decimal,  _
                    ByVal cantidad_19 As Integer,  _
                    ByVal practica_19 As Decimal,  _
                    ByVal cantidad_20 As Integer,  _
                    ByVal practica_20 As Decimal,  _
                    ByVal userState As Object)
            If (Me.wsvo_autorizarOperationCompleted Is Nothing) Then
                Me.wsvo_autorizarOperationCompleted = AddressOf Me.Onwsvo_autorizarOperationCompleted
            End If
            Me.InvokeAsync("wsvo_autorizar", New Object() {financiador, usr, pwd, afiliado, id_empresa, id_prestador, cantidad_1, practica_1, cantidad_2, practica_2, cantidad_3, practica_3, cantidad_4, practica_4, cantidad_5, practica_5, cantidad_6, practica_6, cantidad_7, practica_7, cantidad_8, practica_8, cantidad_9, practica_9, cantidad_10, practica_10, cantidad_11, practica_11, cantidad_12, practica_12, cantidad_13, practica_13, cantidad_14, practica_14, cantidad_15, practica_15, cantidad_16, practica_16, cantidad_17, practica_17, cantidad_18, practica_18, cantidad_19, practica_19, cantidad_20, practica_20}, Me.wsvo_autorizarOperationCompleted, userState)
        End Sub
        
        Private Sub Onwsvo_autorizarOperationCompleted(ByVal arg As Object)
            If (Not (Me.wsvo_autorizarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent wsvo_autorizarCompleted(Me, New wsvo_autorizarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsWSDL#anular", RequestNamespace:="urn:wsWSDL", ResponseNamespace:="urn:wsWSDL")>  _
        Public Function wsvo_anular(ByVal financiador As String, ByVal usr As String, ByVal pwd As String, ByVal id_sucursal As Integer, ByVal id_autorizacion As Integer, ByVal id_prestador As Integer, ByVal numero_afiliado As String, ByVal id_empresa As Integer) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("wsvo_anular", New Object() {financiador, usr, pwd, id_sucursal, id_autorizacion, id_prestador, numero_afiliado, id_empresa})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub wsvo_anularAsync(ByVal financiador As String, ByVal usr As String, ByVal pwd As String, ByVal id_sucursal As Integer, ByVal id_autorizacion As Integer, ByVal id_prestador As Integer, ByVal numero_afiliado As String, ByVal id_empresa As Integer)
            Me.wsvo_anularAsync(financiador, usr, pwd, id_sucursal, id_autorizacion, id_prestador, numero_afiliado, id_empresa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub wsvo_anularAsync(ByVal financiador As String, ByVal usr As String, ByVal pwd As String, ByVal id_sucursal As Integer, ByVal id_autorizacion As Integer, ByVal id_prestador As Integer, ByVal numero_afiliado As String, ByVal id_empresa As Integer, ByVal userState As Object)
            If (Me.wsvo_anularOperationCompleted Is Nothing) Then
                Me.wsvo_anularOperationCompleted = AddressOf Me.Onwsvo_anularOperationCompleted
            End If
            Me.InvokeAsync("wsvo_anular", New Object() {financiador, usr, pwd, id_sucursal, id_autorizacion, id_prestador, numero_afiliado, id_empresa}, Me.wsvo_anularOperationCompleted, userState)
        End Sub
        
        Private Sub Onwsvo_anularOperationCompleted(ByVal arg As Object)
            If (Not (Me.wsvo_anularCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent wsvo_anularCompleted(Me, New wsvo_anularCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsWSDL#verificar_afiliado", RequestNamespace:="urn:wsWSDL", ResponseNamespace:="urn:wsWSDL")>  _
        Public Function wsvo_verificar_afiliado(ByVal financiador As String, ByVal usr As String, ByVal pwd As String, ByVal numero_afiliado As String, ByVal id_empresa As Integer) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("wsvo_verificar_afiliado", New Object() {financiador, usr, pwd, numero_afiliado, id_empresa})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub wsvo_verificar_afiliadoAsync(ByVal financiador As String, ByVal usr As String, ByVal pwd As String, ByVal numero_afiliado As String, ByVal id_empresa As Integer)
            Me.wsvo_verificar_afiliadoAsync(financiador, usr, pwd, numero_afiliado, id_empresa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub wsvo_verificar_afiliadoAsync(ByVal financiador As String, ByVal usr As String, ByVal pwd As String, ByVal numero_afiliado As String, ByVal id_empresa As Integer, ByVal userState As Object)
            If (Me.wsvo_verificar_afiliadoOperationCompleted Is Nothing) Then
                Me.wsvo_verificar_afiliadoOperationCompleted = AddressOf Me.Onwsvo_verificar_afiliadoOperationCompleted
            End If
            Me.InvokeAsync("wsvo_verificar_afiliado", New Object() {financiador, usr, pwd, numero_afiliado, id_empresa}, Me.wsvo_verificar_afiliadoOperationCompleted, userState)
        End Sub
        
        Private Sub Onwsvo_verificar_afiliadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.wsvo_verificar_afiliadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent wsvo_verificar_afiliadoCompleted(Me, New wsvo_verificar_afiliadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub wsvo_autorizarCompletedEventHandler(ByVal sender As Object, ByVal e As wsvo_autorizarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class wsvo_autorizarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub wsvo_anularCompletedEventHandler(ByVal sender As Object, ByVal e As wsvo_anularCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class wsvo_anularCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub wsvo_verificar_afiliadoCompletedEventHandler(ByVal sender As Object, ByVal e As wsvo_verificar_afiliadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class wsvo_verificar_afiliadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
